### ISSUE TITLE
Limit the body bytes read

### ISSUE THREAD

**Issue by diegobernardes** [diegobernardes/flare#106]
With [this](https://golang.org/pkg/net/http/#MaxBytesReader) function, we can limit the quantity of bytes read from the body. The quantity can be set at the configuration file:

```toml
[domain.resource]
max-body-bytes = "100kb"

[domain.subscription]
max-body-bytes = "100kb"

[domain.document]
max-body-bytes = "1mb"
```
